### ISSUE TITLE
question about stim value

### ISSUE THREAD

**Issue by dboas** [fNIRS/snirf#12] opened 2018-11-30 11:32 UTC
Jay wrote:
David and Qianqian,

Had a question about the stim structure. We now have

stim(n).name
stim(n).data

stim(n).data is a 3 column array where each row corresponds to a stimulus trial and the three columns indicate [starttime duration value].

In Homer2, users can manually reject/toggle stims and we indicate this with various non-zero and non-one values. Assuming we want to preserve this functionality in SNIRF and Homer3, do we use the last column for this purpose?

I didn't see any description in the Spec about the last column. Should we add a short description of it's use?

**Comment by dboas** [comment] 2018-11-30 11:35
Jay, turning stim on and off is data analysis software specific. We can hijack 'value' in stim(n).data for this purpose. As for the spec, for now we can leave value as undefined and people can use it how they like. I believe this spec for stim follows what is used for SPM. We can look that up to see how they define 'value'

**Comment by forihuelaespina** [comment] 2019-01-07 20:03
In this regard, highjacking the scalar "value" might be insufficient. For some experiments, it may be interesting to associate to trials some information more elaborated than just a scalar value; e.g. picture, audio, event information, etc.

**Comment by fangq** [comment] 2019-02-07 22:22
@dboas and @jayd1860, is this issue resolved? if yes, please feel free to close.

**Comment by sstucker** [comment] 2020-11-06 21:18
Closing this-- discussion about an extension of stim/data that resolves the issue is ongoing [here](https://github.com/fNIRS/snirf/issues/47)

**Closed by sstucker** 2020-11-06 21:18 UTC
